# container-based build
sudo: false

language: scala

env:
  global:
    - JAVA_OPTS="-DSKIP_FLAKY=1 -Dsbt.log.noformat=true"

  matrix:
    - PROJECT=finagle-core
    - PROJECT=finagle-exception
    - PROJECT=finagle-exp
    - PROJECT=finagle-http
    - PROJECT=finagle-http2
    - PROJECT=finagle-integration
    - PROJECT=finagle-mux
    - PROJECT=finagle-mysql
    - PROJECT=finagle-netty4
    - PROJECT=finagle-netty4-http
    - PROJECT=finagle-netty3
    - PROJECT=finagle-redis
    - PROJECT=finagle-serversets
    - PROJECT=finagle-stats
    - PROJECT=finagle-thrift
    - PROJECT=finagle-thriftmux
    - PROJECT=finagle-toggle
    - PROJECT=finagle-tunable
    - PROJECT=finagle-zipkin-core
    - PROJECT=finagle-zipkin-scribe

# These directories are cached to S3 at the end of the build
cache:
  directories:
   - $HOME/.m2
   - $HOME/.ivy2
   - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION
   - $HOME/.dodo

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

scala:
  - 2.11.11
  - 2.12.4

jdk:
  - oraclejdk8

notifications:
  slack:
    secure: Xd8uDpC8fR9I6RiVZMHCqQ1MRLyBKrBfWtefRbXoUv4kOmyB+JPtNqe+PqNb18xtMvx5GYHNu+Cqel2m6Z5ZVekTPVKJIoVFvW+NytcF/zE1v0wYuCJdfQm58VMKOskriRZxBf4w3HUkcArc8r1N6AnCY5h35jsrI1ER59lTcso=

before_script:
  # default $SBT_OPTS is irrelevant to sbt lancher
  - unset SBT_OPTS
  - curl -s https://raw.githubusercontent.com/twitter/dodo/develop/bin/build | bash -s -- --no-test finagle
  - travis_retry ./sbt --error ++$TRAVIS_SCALA_VERSION ci:update finagle-memcached/update
  # don't test these projects because they don't pass on travis-ci
  - ./sbt ++$TRAVIS_SCALA_VERSION finagle-memcached/test:compile

script:
  # run for all environments
  - travis_retry ./sbt ++$TRAVIS_SCALA_VERSION coverage "$PROJECT/test" coverageReport

after_success:
  - ./sbt ++$TRAVIS_SCALA_VERSION coverageAggregate
  - bash <(curl -s https://codecov.io/bash)
