# container-based build
sudo: false

language: scala

env:
  global:
    - JAVA_OPTS="-DSKIP_FLAKY=1 -Dsbt.log.noformat=true"

  matrix:
    - PROJECT=finagle-core
    - PROJECT=finagle-exception
    - PROJECT=finagle-exp
    - PROJECT=finagle-http
    - PROJECT=finagle-http2
    - PROJECT=finagle-integration
    - PROJECT=finagle-kestrel
    - PROJECT=finagle-mdns
    - PROJECT=finagle-mux
    - PROJECT=finagle-mysql
    - PROJECT=finagle-netty4
    - PROJECT=finagle-netty4-http
    - PROJECT=finagle-ostrich4
    - PROJECT=finagle-redis
    - PROJECT=finagle-serversets
    - PROJECT=finagle-stats
    - PROJECT=finagle-stream
    - PROJECT=finagle-thrift
    - PROJECT=finagle-thriftmux
    - PROJECT=finagle-toggle
    - PROJECT=finagle-zipkin-core
    - PROJECT=finagle-zipkin

# These directories are cached to S3 at the end of the build
cache:
  directories:
   - $HOME/.m2
   - $HOME/.ivy2
   - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION
   - $HOME/.dodo

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

scala:
  - 2.11.8
  - 2.12.1

jdk:
  - oraclejdk8

notifications:
  hipchat:
    rooms:
      secure: UlvjA1u/K7a/ykVt9hfRksqI5coq9k5fFqpeGCcEmqPOyrkOnCLj21xHHB16SzUfwy3pqjVK+B8kWORB9zaNyalHZm6I11Ba1hfmPXWemH/qA972IN/hdAQxnMVhhnWqJPzuoVlW7WAFxwltPTbAwDMzIczmsyMv+rCc2Xffiks=

before_script:
  # default $SBT_OPTS is irrelevant to sbt lancher
  - unset SBT_OPTS
  - curl -s https://raw.githubusercontent.com/twitter/dodo/develop/bin/build | bash -s -- --no-test finagle
  - travis_retry ./sbt --error ++$TRAVIS_SCALA_VERSION ci:update finagle-memcached/update
  # don't test these projects because they don't pass on travis-ci
  - ./sbt ++$TRAVIS_SCALA_VERSION finagle-memcached/test:compile

script:
  # run for all environments
  - travis_retry ./sbt ++$TRAVIS_SCALA_VERSION coverage "$PROJECT/test" coverageReport

after_success:
  - ./sbt ++$TRAVIS_SCALA_VERSION coverageAggregate
  - bash <(curl -s https://codecov.io/bash)
