dist: trusty
sudo: required

language: scala

env:
  global:
    - JAVA_OPTS="-DSKIP_FLAKY=1 -DSKIP_FLAKY_TRAVIS=1 -Dsbt.log.noformat=true"

  matrix:
    - PROJECT=finagle-core
    - PROJECT=finagle-exception
    - PROJECT=finagle-exp
    - PROJECT=finagle-http
    - PROJECT=finagle-http2
    - PROJECT=finagle-integration
    - PROJECT=finagle-mux
    - PROJECT=finagle-mysql
    - PROJECT=finagle-netty4
    - PROJECT=finagle-netty4-http
    - PROJECT=finagle-netty3
    - PROJECT=finagle-redis
    - PROJECT=finagle-serversets
    - PROJECT=finagle-stats
    - PROJECT=finagle-thrift
    - PROJECT=finagle-thriftmux
    - PROJECT=finagle-toggle
    - PROJECT=finagle-tunable
    - PROJECT=finagle-zipkin-core
    - PROJECT=finagle-zipkin-scribe

# These directories are cached to S3 at the end of the build
cache:
  directories:
   - $HOME/.m2
   - $HOME/.ivy2
   - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION
   - $HOME/.dodo

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

scala:
  - 2.11.12
  - 2.12.6

jdk:
  - oraclejdk8

notifications:
  slack:
    secure: PfUgPphNmKcZLIjTjd46IHBzqB0vkzK8clCqdsUr5taJRHhMSgRg8ks81sUhCmu+hTl3FG+jEzGgqMUvcisS+OziP/8QR/C41f5jdaETfkBE53DZIWVXZ80QRabphRTCbRUfibC39WWrhhLgWCIqzvTM8qsO/43JuQOGLQbuqcs=

before_script:
  - unset SBT_OPTS # default $SBT_OPTS is irrelevant to sbt launcher

script:
  - travis_retry ./sbt ++$TRAVIS_SCALA_VERSION coverage "$PROJECT/test" coverageReport

after_success:
  - ./sbt ++$TRAVIS_SCALA_VERSION coverageAggregate
  - bash <(curl -s https://codecov.io/bash)

stages:
  - dodo
  - memcached
  - test

jobs:
  include:
    - stage: dodo
      script: curl -s https://raw.githubusercontent.com/twitter/dodo/develop/bin/build | bash -s -- --no-test finagle
    - stage: memcached # don't test these projects because they don't pass on travis-ci, compile tests only
      scala: 2.11.12
      script: 
        - travis_retry ./sbt --error ++$TRAVIS_SCALA_VERSION ci:update finagle-memcached/update
        - ./sbt ++$TRAVIS_SCALA_VERSION finagle-memcached/test:compile
    - stage: memcached # multiple definitions with the same name end up as matrix under the given stage
      scala: 2.12.6
      script: 
        - travis_retry ./sbt --error ++$TRAVIS_SCALA_VERSION ci:update finagle-memcached/update
        - ./sbt ++$TRAVIS_SCALA_VERSION finagle-memcached/test:compile
